epochs: 100
model_args:
  latent_layer_out_dim : 64
  encoder_layers_dim : []
  decoder_layers_dim : []
  input_dim : 
data_args: 
  filepath : 
data_loader:
  batch_size : 16
  num_workers : 4
  shuffle : False
optim_name : Adam
optim_args : 
  lr : 1.0e-2
output : output
