epochs: 100
model_args:
  latent_layer_out_dim : 2
  encoder_layers_dim : [64, 128]
  decoder_layers_dim : [64, 128]
  input_dim : 600
data_args: 
  filepath : a.npy
data_loader:
  batch_size : 16
  num_workers : 4
  shuffle : False
optim_name : Adam
optim_args : 
  lr : 1.0e-3
output : output